2025-03-11 23:21:35,642 [INFO] USER:abhinandankumar_giri handlers.py:106:syndicate LOG: Configuration used: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\.syndicate-config-dev
2025-03-11 23:21:37,910 [WARNING] USER:abhinandankumar_giri __init__.py:190:initialize_project_state LOG: [93mConfig is set and generated but project state does not exist, seems that you've come from the previous version.[0m
2025-03-11 23:21:37,911 [WARNING] USER:abhinandankumar_giri __init__.py:193:initialize_project_state LOG: [93mGenerating project state file (.syndicate) from the existing structure...[0m
2025-03-11 23:21:37,929 [INFO] USER:abhinandankumar_giri project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\app\lambdas.
2025-03-11 23:21:37,930 [INFO] USER:abhinandankumar_giri project_state.py:400:_update_lambdas_from_path LOG: Going to add the following 'nodejs' lambda:'sns_handler' to the pending ProjectState.
2025-03-11 23:21:37,930 [INFO] USER:abhinandankumar_giri project_state.py:400:_update_lambdas_from_path LOG: Going to add the following 'nodejs' lambda:'sqs_handler' to the pending ProjectState.
2025-03-11 23:21:37,932 [INFO] USER:abhinandankumar_giri processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 23:21:39,659 [INFO] USER:abhinandankumar_giri project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 23:21:39,660 [INFO] USER:abhinandankumar_giri project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 23:21:40,041 [INFO] USER:abhinandankumar_giri sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 23:21:41,912 [INFO] USER:abhinandankumar_giri handlers.py:142:test LOG: Running tests...
2025-03-11 23:21:41,913 [INFO] USER:abhinandankumar_giri handlers.py:150:test LOG: Tests not found, 'tests' folder is missing in 'C:/Users/abhinandankumar_giri/Desktop/Campus Training/aws/Aws-Lambda/task04'.
2025-03-11 23:21:41,914 [INFO] USER:abhinandankumar_giri helper.py:330:timed LOG: Stage test, elapsed time: 0:00:00.001697
2025-03-11 23:21:41,927 [INFO] USER:abhinandankumar_giri handlers.py:993:assemble LOG: Building artifacts, bundle: task04_250311.232140
2025-03-11 23:21:41,928 [INFO] USER:abhinandankumar_giri project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\jsrc\main\java\com\task04.
2025-03-11 23:21:41,928 [INFO] USER:abhinandankumar_giri project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\src\lambdas.
2025-03-11 23:21:41,929 [INFO] USER:abhinandankumar_giri project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\app\lambdas.
2025-03-11 23:21:41,930 [INFO] USER:abhinandankumar_giri project_state.py:400:_update_lambdas_from_path LOG: Going to add the following 'nodejs' lambda:'sns_handler' to the pending ProjectState.
2025-03-11 23:21:41,930 [INFO] USER:abhinandankumar_giri project_state.py:400:_update_lambdas_from_path LOG: Going to add the following 'nodejs' lambda:'sqs_handler' to the pending ProjectState.
2025-03-11 23:21:41,930 [INFO] USER:abhinandankumar_giri project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\dnapp\lambdas.
2025-03-11 23:21:41,930 [INFO] USER:abhinandankumar_giri project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\swagger_src.
2025-03-11 23:21:41,930 [INFO] USER:abhinandankumar_giri project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\appsync_src.
2025-03-11 23:21:41,933 [INFO] USER:abhinandankumar_giri handlers.py:821:assemble_node LOG: Command assemble node: project_path: app 
2025-03-11 23:21:41,934 [INFO] USER:abhinandankumar_giri nodejs.py:58:assemble_node_lambdas LOG: Going to package lambdas starting by path C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\app
2025-03-11 23:21:41,935 [INFO] USER:abhinandankumar_giri nodejs.py:64:assemble_node_lambdas LOG: Going to build artifact in: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\app\lambdas\sns_handler
2025-03-11 23:21:41,937 [INFO] USER:abhinandankumar_giri nodejs.py:64:assemble_node_lambdas LOG: Going to build artifact in: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\app\lambdas\sqs_handler
2025-03-11 23:21:42,494 [INFO] USER:abhinandankumar_giri nodejs.py:123:install_requirements LOG: Artifacts path: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\.syndicate-config-dev\bundles\task04_250311.232140\sns_handler-1.0
2025-03-11 23:21:42,498 [INFO] USER:abhinandankumar_giri nodejs.py:123:install_requirements LOG: Artifacts path: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\.syndicate-config-dev\bundles\task04_250311.232140\sqs_handler-1.0
2025-03-11 23:21:43,347 [INFO] USER:abhinandankumar_giri helper.py:107:execute_command_by_path LOG: Running the command "npm install"

up to date, audited 1 package in 457ms

found 0 vulnerabilities


2025-03-11 23:21:43,348 [INFO] USER:abhinandankumar_giri nodejs.py:142:install_requirements LOG: No dependencies folder - nothing to copy.
2025-03-11 23:21:43,359 [INFO] USER:abhinandankumar_giri helper.py:107:execute_command_by_path LOG: Running the command "npm install"

up to date, audited 1 package in 439ms

found 0 vulnerabilities


2025-03-11 23:21:43,359 [INFO] USER:abhinandankumar_giri nodejs.py:142:install_requirements LOG: No dependencies folder - nothing to copy.
2025-03-11 23:21:43,372 [INFO] USER:abhinandankumar_giri handlers.py:830:assemble_node LOG: NodeJS artifacts were prepared successfully.
2025-03-11 23:21:43,372 [INFO] USER:abhinandankumar_giri helper.py:330:timed LOG: Stage assemble_node, elapsed time: 0:00:01.439806
2025-03-11 23:21:43,374 [INFO] USER:abhinandankumar_giri helper.py:330:timed LOG: Stage assemble, elapsed time: 0:00:01.446412
2025-03-11 23:21:43,375 [INFO] USER:abhinandankumar_giri handlers.py:1037:package_meta LOG: Package meta, bundle: task04_250311.232140
2025-03-11 23:21:43,375 [INFO] USER:abhinandankumar_giri meta_processor.py:513:create_meta LOG: Bundle path: C:/Users/abhinandankumar_giri/Desktop/Campus Training/aws/Aws-Lambda/task04/bundles/task04_250311.232140
2025-03-11 23:21:43,378 [INFO] USER:abhinandankumar_giri helper.py:292:write_content_to_file LOG: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\.syndicate-config-dev/bundles/task04_250311.232140\build_meta.json file was created.
2025-03-11 23:21:43,379 [INFO] USER:abhinandankumar_giri handlers.py:1040:package_meta LOG: Meta was configured successfully.
2025-03-11 23:21:43,379 [INFO] USER:abhinandankumar_giri helper.py:330:timed LOG: Stage package_meta, elapsed time: 0:00:00.003498
2025-03-11 23:21:43,650 [INFO] USER:abhinandankumar_giri handlers.py:1083:upload LOG: Upload bundle: task04_250311.232140
2025-03-11 23:21:44,062 [INFO] USER:abhinandankumar_giri bundle_processor.py:232:upload_bundle_to_s3 LOG: Bundle was validated successfully
2025-03-11 23:21:45,443 [INFO] USER:abhinandankumar_giri handlers.py:1090:upload LOG: Bundle was uploaded successfully
2025-03-11 23:21:45,444 [INFO] USER:abhinandankumar_giri helper.py:330:timed LOG: Stage upload, elapsed time: 0:00:02.063333
2025-03-11 23:21:45,449 [INFO] USER:abhinandankumar_giri helper.py:330:timed LOG: Stage build, elapsed time: 0:00:05.406801
2025-03-11 23:24:00,153 [INFO] USER:abhinandankumar_giri handlers.py:106:syndicate LOG: Configuration used: C:\Users\abhinandankumar_giri\Desktop\Campus Training\aws\Aws-Lambda\task04\.syndicate-config-dev
2025-03-11 23:24:02,412 [INFO] USER:abhinandankumar_giri processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 23:24:04,044 [INFO] USER:abhinandankumar_giri project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 23:24:04,044 [INFO] USER:abhinandankumar_giri project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 23:24:04,451 [INFO] USER:abhinandankumar_giri sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 23:24:04,866 [INFO] USER:abhinandankumar_giri project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 23:24:04,866 [INFO] USER:abhinandankumar_giri project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 23:24:05,270 [INFO] USER:abhinandankumar_giri sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 23:24:05,271 [INFO] USER:abhinandankumar_giri helper.py:233:resolve_default_value LOG: Resolved value of deploy_name: task04
2025-03-11 23:24:05,685 [INFO] USER:abhinandankumar_giri project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 23:24:05,685 [INFO] USER:abhinandankumar_giri project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 23:24:06,090 [INFO] USER:abhinandankumar_giri sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 23:24:06,090 [INFO] USER:abhinandankumar_giri helper.py:233:resolve_default_value LOG: Resolved value of bundle_name: task04_250311.232140
2025-03-11 23:24:06,505 [INFO] USER:abhinandankumar_giri project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 23:24:06,505 [INFO] USER:abhinandankumar_giri project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 23:24:06,910 [INFO] USER:abhinandankumar_giri sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 23:24:07,331 [INFO] USER:abhinandankumar_giri project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 23:24:07,331 [INFO] USER:abhinandankumar_giri project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 23:24:07,696 [INFO] USER:abhinandankumar_giri sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 23:24:10,083 [INFO] USER:abhinandankumar_giri deployment_processor.py:466:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved
2025-03-11 23:24:10,083 [INFO] USER:abhinandankumar_giri deployment_processor.py:489:create_deployment_resources LOG: Going to deploy AWS resources
2025-03-11 23:24:10,370 [INFO] USER:abhinandankumar_giri deployment_processor.py:74:_process_resources LOG: Processing iam_policy resources
2025-03-11 23:24:11,990 [WARNING] USER:abhinandankumar_giri iam_resource.py:115:_create_policy_from_meta LOG: IAM policy cmtr-3bfb6220-lambda-basic-execution exists.
2025-03-11 23:24:12,444 [INFO] USER:abhinandankumar_giri deployment_processor.py:74:_process_resources LOG: Processing iam_role resources
2025-03-11 23:24:14,180 [WARNING] USER:abhinandankumar_giri iam_resource.py:141:_create_role_from_meta LOG: IAM role cmtr-3bfb6220-sqs_handler-role exists.
2025-03-11 23:24:14,194 [ERROR] USER:abhinandankumar_giri deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-3bfb6220-sns_handler-role. Parameter validation failed:
Invalid length for parameter PermissionsBoundary, value: 9, valid min length: 20
2025-03-11 23:24:14,195 [INFO] USER:abhinandankumar_giri deployment_processor.py:74:_process_resources LOG: Processing sns_topic resources
2025-03-11 23:24:15,723 [ERROR] USER:abhinandankumar_giri deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-3bfb6220-lambda_topic. An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:sts::890742610830:assumed-role/cmtr_syndicate_student_programmatic_accessv2/3bfb6220 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:eu-central-1:890742610830:* with an explicit deny in a service control policy
2025-03-11 23:24:15,724 [INFO] USER:abhinandankumar_giri deployment_processor.py:74:_process_resources LOG: Processing sqs_queue resources
2025-03-11 23:24:17,147 [WARNING] USER:abhinandankumar_giri sqs_resource.py:104:_create_sqs_queue_from_meta LOG: SQS queue cmtr-3bfb6220-async_queue exists.
2025-03-11 23:24:17,353 [INFO] USER:abhinandankumar_giri deployment_processor.py:88:_process_resources LOG: Processing lambda resources
2025-03-11 23:24:23,292 [INFO] USER:abhinandankumar_giri lambda_resource.py:1394:_resolve_log_group LOG: Cloud Watch log group for lambda: cmtr-3bfb6220-sqs_handler does not exists. Creating new log group with name: aws/lambda/cmtr-3bfb6220-sqs_handler
2025-03-11 23:24:26,369 [WARNING] USER:abhinandankumar_giri helper.py:121:wrapper LOG: Retry on add_event_source. Error: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: The function execution role does not have permissions to call ReceiveMessage on SQS
2025-03-11 23:24:27,796 [WARNING] USER:abhinandankumar_giri helper.py:121:wrapper LOG: Retry on add_event_source. Error: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: The function execution role does not have permissions to call ReceiveMessage on SQS
2025-03-11 23:24:32,199 [WARNING] USER:abhinandankumar_giri helper.py:121:wrapper LOG: Retry on add_event_source. Error: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: The function execution role does not have permissions to call ReceiveMessage on SQS
2025-03-11 23:24:39,503 [WARNING] USER:abhinandankumar_giri helper.py:121:wrapper LOG: Retry on add_event_source. Error: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: The function execution role does not have permissions to call ReceiveMessage on SQS
2025-03-11 23:24:49,838 [WARNING] USER:abhinandankumar_giri helper.py:121:wrapper LOG: Retry on add_event_source. Error: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: The function execution role does not have permissions to call ReceiveMessage on SQS
2025-03-11 23:25:03,207 [WARNING] USER:abhinandankumar_giri helper.py:121:wrapper LOG: Retry on add_event_source. Error: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: The function execution role does not have permissions to call ReceiveMessage on SQS
2025-03-11 23:25:19,610 [WARNING] USER:abhinandankumar_giri helper.py:121:wrapper LOG: Retry on add_event_source. Error: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: The function execution role does not have permissions to call ReceiveMessage on SQS
2025-03-11 23:25:38,980 [WARNING] USER:abhinandankumar_giri helper.py:121:wrapper LOG: Retry on add_event_source. Error: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: The function execution role does not have permissions to call ReceiveMessage on SQS
2025-03-11 23:26:01,331 [WARNING] USER:abhinandankumar_giri helper.py:121:wrapper LOG: Retry on add_event_source. Error: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: The function execution role does not have permissions to call ReceiveMessage on SQS
